# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ime/ui/ui_access_control_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AccessControlTab(object):
    def setupUi(self, AccessControlTab):
        AccessControlTab.setObjectName("AccessControlTab")
        AccessControlTab.resize(725, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(AccessControlTab.sizePolicy().hasHeightForWidth())
        AccessControlTab.setSizePolicy(sizePolicy)
        AccessControlTab.setMinimumSize(QtCore.QSize(400, 500))
        self.formLayout = QtWidgets.QFormLayout(AccessControlTab)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(-1, -1, -1, 20)
        self.formLayout.setObjectName("formLayout")
        self.label_29 = QtWidgets.QLabel(AccessControlTab)
        self.label_29.setObjectName("label_29")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.usersList = AccessControlList(AccessControlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.usersList.sizePolicy().hasHeightForWidth())
        self.usersList.setSizePolicy(sizePolicy)
        self.usersList.setObjectName("usersList")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usersList)
        self.label_30 = QtWidgets.QLabel(AccessControlTab)
        self.label_30.setObjectName("label_30")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.groupsList = AccessControlList(AccessControlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupsList.sizePolicy().hasHeightForWidth())
        self.groupsList.setSizePolicy(sizePolicy)
        self.groupsList.setObjectName("groupsList")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.groupsList)

        self.retranslateUi(AccessControlTab)
        QtCore.QMetaObject.connectSlotsByName(AccessControlTab)

    def retranslateUi(self, AccessControlTab):
        _translate = QtCore.QCoreApplication.translate
        AccessControlTab.setWindowTitle(_translate("AccessControlTab", "Form"))
        self.label_29.setText(_translate("AccessControlTab", "Users"))
        self.label_30.setText(_translate("AccessControlTab", "Groups"))
from ime.widgets.access_control_list import AccessControlList
