# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ime/ui/ui_derived_access_control_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DerivedAccessControlTab(object):
    def setupUi(self, DerivedAccessControlTab):
        DerivedAccessControlTab.setObjectName("DerivedAccessControlTab")
        DerivedAccessControlTab.resize(725, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(DerivedAccessControlTab.sizePolicy().hasHeightForWidth())
        DerivedAccessControlTab.setSizePolicy(sizePolicy)
        DerivedAccessControlTab.setMinimumSize(QtCore.QSize(400, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(DerivedAccessControlTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(DerivedAccessControlTab)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(DerivedAccessControlTab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usersOverride = QtWidgets.QCheckBox(DerivedAccessControlTab)
        self.usersOverride.setObjectName("usersOverride")
        self.gridLayout.addWidget(self.usersOverride, 2, 1, 1, 1)
        self.groupsOverride = QtWidgets.QCheckBox(DerivedAccessControlTab)
        self.groupsOverride.setObjectName("groupsOverride")
        self.gridLayout.addWidget(self.groupsOverride, 0, 1, 1, 1)
        self.users = AccessControlList(DerivedAccessControlTab)
        self.users.setObjectName("users")
        self.gridLayout.addWidget(self.users, 3, 1, 1, 1)
        self.groups = AccessControlList(DerivedAccessControlTab)
        self.groups.setObjectName("groups")
        self.gridLayout.addWidget(self.groups, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DerivedAccessControlTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(DerivedAccessControlTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(DerivedAccessControlTab)
        QtCore.QMetaObject.connectSlotsByName(DerivedAccessControlTab)

    def retranslateUi(self, DerivedAccessControlTab):
        _translate = QtCore.QCoreApplication.translate
        DerivedAccessControlTab.setWindowTitle(_translate("DerivedAccessControlTab", "Form"))
        self.label_3.setText(_translate("DerivedAccessControlTab", "You can control the users and groups who can access this object. These settings apply to all data in this object, unless overridden."))
        self.label_4.setText(_translate("DerivedAccessControlTab", "Groups and users added here will have access to data in this object. You can grant additional rights like ownership, download and see sensitive metadata."))
        self.usersOverride.setText(_translate("DerivedAccessControlTab", "Override"))
        self.groupsOverride.setText(_translate("DerivedAccessControlTab", "Override"))
        self.label_2.setText(_translate("DerivedAccessControlTab", "Users"))
        self.label.setText(_translate("DerivedAccessControlTab", "Groups"))
from ime.widgets.access_control_list import AccessControlList
