# Form implementation generated from reading ui file 'ime/ui/ui_datafile_props.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DatafilePropertyEditor(object):
    def setupUi(self, DatafilePropertyEditor):
        DatafilePropertyEditor.setObjectName("DatafilePropertyEditor")
        DatafilePropertyEditor.resize(518, 300)
        self.gridLayout = QtWidgets.QGridLayout(DatafilePropertyEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox_4 = QtWidgets.QToolBox(parent=DatafilePropertyEditor)
        self.toolBox_4.setMinimumSize(QtCore.QSize(500, 0))
        self.toolBox_4.setObjectName("toolBox_4")
        self.fileinfoDescription = QtWidgets.QWidget()
        self.fileinfoDescription.setGeometry(QtCore.QRect(0, 0, 506, 180))
        self.fileinfoDescription.setObjectName("fileinfoDescription")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.fileinfoDescription)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.fileInfoFilenameLabel = QtWidgets.QLabel(parent=self.fileinfoDescription)
        self.fileInfoFilenameLabel.setObjectName("fileInfoFilenameLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.fileInfoFilenameLabel)
        self.fileInfoFilenameLineEdit = QtWidgets.QLineEdit(parent=self.fileinfoDescription)
        self.fileInfoFilenameLineEdit.setEnabled(False)
        self.fileInfoFilenameLineEdit.setObjectName("fileInfoFilenameLineEdit")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.fileInfoFilenameLineEdit)
        self.gridLayout_7.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.toolBox_4.addItem(self.fileinfoDescription, "")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.page_10.setObjectName("page_10")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.accessControlTab = OverridableAccessControlTab(parent=self.page_10)
        self.accessControlTab.setObjectName("accessControlTab")
        self.gridLayout_2.addWidget(self.accessControlTab, 0, 0, 1, 1)
        self.toolBox_4.addItem(self.page_10, "")
        self.metadata_tab = MetadataTab()
        self.metadata_tab.setGeometry(QtCore.QRect(0, 0, 96, 26))
        self.metadata_tab.setObjectName("metadata_tab")
        self.toolBox_4.addItem(self.metadata_tab, "")
        self.gridLayout.addWidget(self.toolBox_4, 0, 0, 1, 1)

        self.retranslateUi(DatafilePropertyEditor)
        self.toolBox_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DatafilePropertyEditor)

    def retranslateUi(self, DatafilePropertyEditor):
        _translate = QtCore.QCoreApplication.translate
        DatafilePropertyEditor.setWindowTitle(_translate("DatafilePropertyEditor", "Form"))
        self.fileInfoFilenameLabel.setText(_translate("DatafilePropertyEditor", "Filename"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.fileinfoDescription), _translate("DatafilePropertyEditor", "General"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.page_10), _translate("DatafilePropertyEditor", "User and group access"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.metadata_tab), _translate("DatafilePropertyEditor", "Metadata"))
from ime.widgets.metadata_tab import MetadataTab
from ime.widgets.overridable_access_control_tab import OverridableAccessControlTab
