# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ime/ui/ui_extraction_progress_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExtractionProgressDialog(object):
    def setupUi(self, ExtractionProgressDialog):
        ExtractionProgressDialog.setObjectName("ExtractionProgressDialog")
        ExtractionProgressDialog.resize(518, 112)
        ExtractionProgressDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(ExtractionProgressDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ExtractionProgressDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(ExtractionProgressDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.fileName = QtWidgets.QLabel(ExtractionProgressDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileName.sizePolicy().hasHeightForWidth())
        self.fileName.setSizePolicy(sizePolicy)
        self.fileName.setText("")
        self.fileName.setWordWrap(True)
        self.fileName.setObjectName("fileName")
        self.verticalLayout.addWidget(self.fileName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ExtractionProgressDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(ExtractionProgressDialog)
        self.buttonBox.accepted.connect(ExtractionProgressDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ExtractionProgressDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ExtractionProgressDialog)

    def retranslateUi(self, ExtractionProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        ExtractionProgressDialog.setWindowTitle(_translate("ExtractionProgressDialog", "Finishing data file import"))
        self.label.setText(_translate("ExtractionProgressDialog", "Extracting metadata from images..."))
