# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ime/ui/ui_identifier_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IdentifierList(object):
    def setupUi(self, IdentifierList):
        IdentifierList.setObjectName("IdentifierList")
        IdentifierList.resize(748, 620)
        self.gridLayout = QtWidgets.QGridLayout(IdentifierList)
        self.gridLayout.setObjectName("gridLayout")
        self.identifierList = QtWidgets.QListView(IdentifierList)
        self.identifierList.setObjectName("identifierList")
        self.gridLayout.addWidget(self.identifierList, 0, 0, 1, 2)
        self.btnAdd = QtWidgets.QPushButton(IdentifierList)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 1, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(IdentifierList)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 1, 1, 1, 1)

        self.retranslateUi(IdentifierList)
        QtCore.QMetaObject.connectSlotsByName(IdentifierList)

    def retranslateUi(self, IdentifierList):
        _translate = QtCore.QCoreApplication.translate
        IdentifierList.setWindowTitle(_translate("IdentifierList", "Form"))
        self.btnAdd.setText(_translate("IdentifierList", "Add..."))
        self.btnDelete.setText(_translate("IdentifierList", "Remove"))
