# Form implementation generated from reading ui file 'ime/ui/ui_overridable_access_control_tab.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverridableAccessControlTab(object):
    def setupUi(self, OverridableAccessControlTab):
        OverridableAccessControlTab.setObjectName("OverridableAccessControlTab")
        OverridableAccessControlTab.resize(725, 1080)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(OverridableAccessControlTab.sizePolicy().hasHeightForWidth())
        OverridableAccessControlTab.setSizePolicy(sizePolicy)
        OverridableAccessControlTab.setMinimumSize(QtCore.QSize(400, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(OverridableAccessControlTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=OverridableAccessControlTab)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=OverridableAccessControlTab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.usersOverride = QtWidgets.QCheckBox(parent=OverridableAccessControlTab)
        self.usersOverride.setObjectName("usersOverride")
        self.gridLayout.addWidget(self.usersOverride, 2, 1, 1, 1)
        self.groupsOverride = QtWidgets.QCheckBox(parent=OverridableAccessControlTab)
        self.groupsOverride.setObjectName("groupsOverride")
        self.gridLayout.addWidget(self.groupsOverride, 0, 1, 1, 1)
        self.users = AccessControlList(parent=OverridableAccessControlTab)
        self.users.setObjectName("users")
        self.gridLayout.addWidget(self.users, 3, 1, 1, 1)
        self.groups = AccessControlList(parent=OverridableAccessControlTab)
        self.groups.setObjectName("groups")
        self.gridLayout.addWidget(self.groups, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=OverridableAccessControlTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=OverridableAccessControlTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(OverridableAccessControlTab)
        QtCore.QMetaObject.connectSlotsByName(OverridableAccessControlTab)

    def retranslateUi(self, OverridableAccessControlTab):
        _translate = QtCore.QCoreApplication.translate
        OverridableAccessControlTab.setWindowTitle(_translate("OverridableAccessControlTab", "Form"))
        self.label_3.setText(_translate("OverridableAccessControlTab", "You can control the users and groups who can access this object. These settings apply to all data in this object, unless overridden."))
        self.label_4.setText(_translate("OverridableAccessControlTab", "Groups and users added here will have access to data in this object. You can grant additional rights like ownership, download and see sensitive metadata."))
        self.usersOverride.setText(_translate("OverridableAccessControlTab", "Override"))
        self.groupsOverride.setText(_translate("OverridableAccessControlTab", "Override"))
        self.label_2.setText(_translate("OverridableAccessControlTab", "Users"))
        self.label.setText(_translate("OverridableAccessControlTab", "Groups"))
from ime.widgets.access_control_list import AccessControlList
