# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ime/ui/ui_project_props.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectPropertyEditor(object):
    def setupUi(self, ProjectPropertyEditor):
        ProjectPropertyEditor.setObjectName("ProjectPropertyEditor")
        ProjectPropertyEditor.resize(524, 553)
        self.gridLayout = QtWidgets.QGridLayout(ProjectPropertyEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox_3 = QtWidgets.QToolBox(ProjectPropertyEditor)
        self.toolBox_3.setMinimumSize(QtCore.QSize(500, 0))
        self.toolBox_3.setObjectName("toolBox_3")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 500, 427))
        self.page_7.setObjectName("page_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.page_7)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.projectNameLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.projectNameLineEdit)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.projectDescriptionLineEdit = QtWidgets.QPlainTextEdit(self.frame_3)
        self.projectDescriptionLineEdit.setObjectName("projectDescriptionLineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.projectDescriptionLineEdit)
        self.leadResearcherLabel = QtWidgets.QLabel(self.frame_3)
        self.leadResearcherLabel.setObjectName("leadResearcherLabel")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.leadResearcherLabel)
        self.leadResearcherLineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.leadResearcherLineEdit.setObjectName("leadResearcherLineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.leadResearcherLineEdit)
        self.identifierList = IdentifierList(self.frame_3)
        self.identifierList.setObjectName("identifierList")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.identifierList)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.toolBox_3.addItem(self.page_7, "")
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setGeometry(QtCore.QRect(0, 0, 98, 34))
        self.page_8.setObjectName("page_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.accessControlTab = ProjectAccessControlTab(self.page_8)
        self.accessControlTab.setObjectName("accessControlTab")
        self.gridLayout_4.addWidget(self.accessControlTab, 0, 0, 1, 1)
        self.toolBox_3.addItem(self.page_8, "")
        self.metadata_tab = MetadataTab()
        self.metadata_tab.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.metadata_tab.setObjectName("metadata_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.metadata_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.toolBox_3.addItem(self.metadata_tab, "")
        self.gridLayout.addWidget(self.toolBox_3, 0, 0, 1, 1)

        self.retranslateUi(ProjectPropertyEditor)
        self.toolBox_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProjectPropertyEditor)

    def retranslateUi(self, ProjectPropertyEditor):
        _translate = QtCore.QCoreApplication.translate
        ProjectPropertyEditor.setWindowTitle(_translate("ProjectPropertyEditor", "Form"))
        self.label_3.setText(_translate("ProjectPropertyEditor", "Project name"))
        self.label_5.setText(_translate("ProjectPropertyEditor", "Identifiers"))
        self.label_27.setText(_translate("ProjectPropertyEditor", "Description"))
        self.leadResearcherLabel.setText(_translate("ProjectPropertyEditor", "Principal Investigator"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_7), _translate("ProjectPropertyEditor", "General"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_8), _translate("ProjectPropertyEditor", "User and group access"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.metadata_tab), _translate("ProjectPropertyEditor", "Metadata"))
from ime.widgets.identifier_list import IdentifierList
from ime.widgets.metadata_tab import MetadataTab
from ime.widgets.project_access_control_tab import ProjectAccessControlTab
