name: Build executables
on:
  push:
    branches: 
      - main
      - IDS-358-add-bioformats-jar-in-installer
jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: Install poetry
        run: poetry install
      - name: Build executable
        run: poetry run pyinstaller pyinstaller.spec
      - name: Pack in tarball to prevent macOS and linux permission loss
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: tar -cvf dist.tar dist
      - name: Upload artifact to make it available (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{matrix.os}}
          path: dist/*
      - name: Upload artifact to make it available (macOS and Linux)
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{matrix.os}}
          path: dist.tar