name: Build executables
on:
  push:
    branches: 
      - main
      - IDS-358-add-bioformats-jar-in-installer
jobs:
  ci:
    strategy:
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.4.1"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install poetry
        run: poetry install
      - name: Build executable
        run: poetry run pyinstaller pyinstaller.spec
      - name: Upload artifact to make it available
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{matrix.os}}
          path: dist/*