name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    env:
      DISPLAY: "99.0"
      QT_SELECT: "qt6"
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup OS
      run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libxcb-shape0 libglib2.0-0 libgl1-mesa-dev
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt-get install -y openjdk
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Update Poetry lock file
      run: poetry lock
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: isort - check import formatting
      if: always()
      run: PYTHONPATH=ime/ poetry run python -m isort --check --diff --profile black --skip=ime/ui/ ime

    - name: Black - check code formatting
      if: always()
      run: PYTHONPATH=ime/ poetry run python -m black --check --diff --extend-exclude ime/ui/ ime

    - name: pylint - static code analysis
      if: always()
      run: PYTHONPATH=ime/ poetry run python -m pylint ime/ --rcfile .pylintrc

    - name: mypy - static type checking
      if: always()
      # Takes configuration from pyproject.toml
      run: PYTHONPATH=ime/ poetry run python -m mypy

    - name: pytest - run the tests
      if: always()
      run: PYTHONPATH=ime/ poetry run python -m pytest -v ime/tests/
