name: Test and Lint

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Update Poetry lock file
      run: poetry lock
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: isort - check import formatting
      run: PYTHONPATH=src/ poetry run python -m isort --check --diff --profile black ime

    - name: Black - check code formatting
      run: PYTHONPATH=src/ poetry run python -m black --check --diff ime

    - name: pylint - static code analysis
      run: PYTHONPATH=src/ poetry run python -m pylint ime/ --rcfile .pylintrc

    - name: mypy - static type checking
      # Takes configuration from pyproject.toml
      run: PYTHONPATH=src/ poetry run python -m mypy

    - name: pytest - run the tests
      run: PYTHONPATH=src/ poetry run python -m pytest -v --cov=ime/ tests/
